{% set base_name = "libignition-transport" %}
{% set version = "8.0.0" %}
{% set major_version = version.split('.')[0] %}
{% set name = base_name + major_version %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://bitbucket.org/ignitionrobotics/ign-transport/get/ignition-transport{{ major_version }}_{{ version }}.tar.gz
    sha256: 9e569b5f262aa967712a0e4bab3962d9d210cfd61d442d5798f3cc550e8adbe7

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}              # [not win]
    - {{ compiler('c') }}                # [not win]
    - vs2017_win-64                      # [win64]
    - vs2017_win-32                      # [win32]
    - make                               # [not win]
    - cmake
    - pkg-config
  host:
    - libignition-msgs5
    - cppzmq
    - zeromq
    - libuuid                            # [not win]
    - libprotobuf                        # [not win]
  run:
    - libignition-msgs5
    - cppzmq
    - zeromq
    - libuuid                            # [not win]
    - libprotobuf                        # [not win]

test:
  commands:
    - test -f ${PREFIX}/include/ignition/transport{{ major_version }}/ignition/transport.hh  # [not win]
    - test -f ${PREFIX}/lib/libignition-transport{{ major_version }}.so  # [linux]
    - test -f ${PREFIX}/lib/libignition-transport{{ major_version }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/cmake/ignition-transport{{ major_version }}/ignition-transport{{ major_version }}-config.cmake  # [not win]
    - if exist %PREFIX%\\Library\\include\\ignition\\transport{{ major_version }}\\ignition\\transport.hh (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\lib\\ignition-transport{{ major_version }}.lib (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\bin\\ignition-transport{{ major_version }}.dll (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\lib\\cmake\\ignition-transport{{ major_version }}\\ignition-transport{{ major_version }}-config.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://bitbucket.org/ignitionrobotics/ign-transport
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Ignition Transport'

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
    - traversaro
    - j-rivero
